### ISSUE TITLE
its not working why 

### ISSUE THREAD

**Issue by hadoizz** [CybriaTech/CybriaGG#1]
hey how are you i tried the links but not working is there a way to fix /

**Comment by ghost** [comment]
yea, its still experimental. The official links aren´t always active, like Replit due to their new policies and CybriaTech since I didnt rlly set it up yet.

Im working on finding an official link.

**Comment by ghost** [comment]
also, extra stuff. If you wanna fork, maybe deploy ur own. like Codespaces, Codesandbox, Glitch or even StackBlitz (free)
